// This file is generated by Slice Machine. Update with care!

import ImageGrid from "./ImageGrid";
import ImageWithText from "./ImageWithText";
import QuoteByImage from "./QuoteByImage";
import QuoteByText from "./QuoteByText";
import TextByText from "./TextByText";

export { ImageGrid, ImageWithText, QuoteByImage, QuoteByText, TextByText };

export const components = {
  image_grid: ImageGrid,
  image_with_text: ImageWithText,
  quote_by_image: QuoteByImage,
  quote_by_text: QuoteByText,
  text_by_text: TextByText,
};
