// This file is generated by Slice Machine. Update with care!

export { default as ImageWithText } from "./ImageWithText";
export { default as QuoteByImage } from "./QuoteByImage";
export { default as TextByText } from "./TextByText";
